Update getting-started.md to reflect DevOps's new doc
DataBiosphere/terra-data-catalog pull request #76
Opened 2022-05-03 15:10 UTC by jack-r-warren

Re-ordered some steps and took out the parts that duplicate what we have in the doc. _Please feel free to update this branch and change whatever_, just figured I'd link to the new thing.

2022-05-03 21:18 UTC, pshapiro4broad approved these changes
LGTM

2022-05-04 18:08 UTC, fboulnois requested changes
Please don't merge yet, I'd like to have in internal discussion with the team first. Thanks!

2022-05-04 18:43 UTC, tcjiang9 approved these changes

2022-05-04 19:17 UTC, pshapiro4broad commented
After a discussion with the team, we've decided to close this PR instead of merging it. The consensus was that we are OK to have some duplication of documentation in the interest of having all the onboarding text in a single place. @fboulnois will be updating the getting started doc in a separate PR that will include, among other changes, a link to the new DevOps doc.

2022-05-04 19:17 UTC, closed without merging